service: northwind
frameworkVersion: '3'
plugins:
  - serverless-webpack
  - serverless-offline
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB: ${env:DB}

functions:
  getSuppliers:
    handler: src/functions/getSuppliers/handler.main
    events:
      - http:
          path: /suppliers
          method: get
          cors: true

  getSupplier:
    handler: src/functions/getSupplier/handler.main
    events:
      - http:
          path: /supplier
          method: get
          cors: true

  getProducts:
    handler: src/functions/getProducts/handler.main
    events:
      - http:
          path: /products
          method: get
          cors: true

  getProduct:
    handler: src/functions/getProduct/handler.main
    events:
      - http:
          path: /product
          method: get
          cors: true

  getOrders:
    handler: src/functions/getOrders/handler.main
    events:
      - http:
          path: /orders
          method: get
          cors: true

  getOrder:
    handler: src/functions/getOrder/handler.main
    events:
      - http:
          path: /order
          method: get
          cors: true

  getEmployees:
    handler: src/functions/getEmployees/handler.main
    events:
      - http:
          path: /employees
          method: get
          cors: true

  getEmployee:
    handler: src/functions/getEmployee/handler.main
    events:
      - http:
          path: /employee
          method: get
          cors: true

  getCustomers:
    handler: src/functions/getCustomers/handler.main
    events:
      - http:
          path: /customers
          method: get
          cors: true

  getCustomer:
    handler: src/functions/getCustomer/handler.main
    events:
      - http:
          path: /customer
          method: get
          cors: true

  search:
    handler: src/functions/search/handler.main
    events:
      - http:
          path: /search
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                q: true
                table: true

# package:
#   individually: true

custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: true
    packager: npm